# Generated by Django 5.2.7 on 2025-10-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0003_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='shipping_address',
        ),
    ]
