# Generated by Django 5.2.7 on 2025-10-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0004_rename_amount_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=350, null=True),
        ),
    ]
